Parameters:
  AmiId:
    Type: AWS::EC2::Image::Id

Resources:
  AppLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: schedemy01-template
      LaunchTemplateData:
        ImageId: !Ref AmiId
        InstanceType: t3.small
        SecurityGroupIds:
          - sg-0c8a5696248221b71
        IamInstanceProfile:
          Name: Schedemy-instance-profile

  
    UpdatePolicy:
      AutoScalingRollingUpdate:
        MinInstancesInService: 1
        MaxBatchSize: 1

