---
- name: Deploy Spring Boot from S3
  hosts: all
  become: yes
  vars:
    app_dir: /opt/schedemy
    # We will pass this variable from GitHub Actions
    s3_url: "s3://schedemy-bucket/app.jar" 

  tasks:
    - name: Install AWS CLI (needed to pull from S3)
      yum:
        name: aws-cli
        state: present

    - name: Download JAR from S3
      command: "aws s3 cp {{ s3_url }} {{ app_dir }}/EduSched-0.0.1-SNAPSHOT.jar"
      # In production, use the 'aws_s3' ansible module, but 'command' is easier to debug for beginners.

    - name: Restart Spring Boot Service
      service:
        name: schedemy
        state: restarted
