# AWS EC2 Dynamic Inventory Configuration
# This file tells Ansible how to automatically discover EC2 instances

# Plugin to use - aws_ec2 is for discovering EC2 instances
plugin: aws_ec2

# AWS region where your instances are located
regions:
  - us-east-1

# Filters to find specific EC2 instances
# This is like saying "only show me instances that match these criteria"
filters:
  # Only find instances that are currently running (not stopped or terminated)
  instance-state-name: running
  
  # Only find instances with this specific tag
  # Make sure your ASG instances have this tag!
  tag:Name: schedemyASGinstance

# How to organize instances into groups
# This creates groups like "tag_Environment_production"
keyed_groups:
  # Group by instance tags
  - key: tags
    prefix: tag
  
  # Group by instance type (t2.micro, t3.small, etc.)
  - key: instance_type
    prefix: instance_type
  
  # Group by availability zone
  - key: placement.availability_zone
    prefix: az

# What to use as the hostname when connecting
# Options: public-ip-address, private-ip-address, dns-name, etc.
hostnames:
  - ip-address  # Uses public IP by default

# Should we compose more complex variables?
compose:
  # Create a friendly name variable
  ansible_host: public_ip_address
  
  # Add the instance ID as a variable
  ec2_instance_id: instance_id
  
  # Add the instance type as a variable
  ec2_instance_type: instance_type

# Use cache to speed up repeated inventory queries
cache: yes
cache_plugin: jsonfile
cache_timeout: 300
cache_connection: /tmp/aws_inventory_cache
cache_prefix: aws_ec2

# Note: For this to work, you need:
# 1. AWS credentials configured (AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY)
# 2. EC2 instances must be tagged with Name=schedemyASGinstance
# 3. boto3 and botocore Python libraries installed
